### ISSUE TITLE
นี่คือ Open Source ที่ Aktah เคยแจกใช่ไหมครับ

### ISSUE THREAD

**Issue by JIRAMATEDEV** [Peejay38Dev/sourcesampmobile#1]

**Comment by Peejay38Dev** [comment]
ไม่ใช่ครับ Source ที่ผมทำเองครับ

**Comment by JIRAMATEDEV** [comment]
แต่ที่ผมเช็คแล้วนี้มันอันเดียวกันเลย

**Comment by JIRAMATEDEV** [comment]
แต่ที่แจกก็ดีแล้วครับให้คนมาศึกษาการทำ APK

**Comment by Peejay38Dev** [comment]
ตัวนี้เป็นตัว Source 80 % ตัวไหนไม่เข้าใจผมลอกมาจาก Aktah 20 % ครับ

ในวันที่ พฤ. 17 ต.ค. 2019 15:59 น. JIRAMATEDEV <notifications@github.com>
เขียนว่า:
